
spring:
  datasource:
      url: 'jdbc:mysql://192.168.10.93:3306/springcloud?useUnicode=true&characterEncoding=utf-8'
      username: root
      password: '{cipher}1a8db426693755beb3b3c99fe3cc681ab9d0c5539779b35f50ccada1ba61b878'
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

encrypt:
  key: 'xian'

#日志
log:
  path: E:\\logback\\user-service
  level: info