server:  
  port: ${PORT:2222}

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
#      username: micro
#      password: micro
  rabbitmq:
      host: localhost
      username: springcloud
      password: 123456
          
ribbon:
  eureka:
    enabled: true
    
test:
  accounts:
    - id: 1
      number: '0654321789'
      balance: 9999
      customerId: 1
    - id: 2
      number: '0654321780'
      balance: 0
      customerId: 1
    - id: 3
      number: '0650981789'
      balance: 12555
      customerId: 2
